"""``.slurm`` template generator for sweep array jobs.

Mirrors the structure of ``Autoencoder_SLURMChoice_10_SLURMIDX_1.slurm``
but invokes the Python pipeline instead of MATLAB. Each emitted file
is a self-contained sbatch script that uses a SLURM array task ID as
the ``SessionRunIDX`` (MATLAB-style decomposition into session × fold,
preserving fold-across-sessions ordering).

Example use::

    python -m neural_data_decoding sweep-emit-slurm \\
        --sweep-index 10 --config-name real_data_base \\
        --output-path Output_Files/sweep_10.slurm

The emitted file is intended to be edited freely — paths, time limits,
and memory budgets are typically site-specific. The generator just
captures the conventions the MATLAB pipeline established (output dir,
array sequencing, mail-user gating on user identity).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from neural_data_decoding.sweeps.dispatcher import lookup as _lookup_sweep
from neural_data_decoding.sweeps.user_identity import (
    UserIdentity,
    identify_user,
    maybe_default_mail,
)


# Defaults match the MATLAB sample SLURM file the user supplied
# (Autoencoder_SLURMChoice_10_SLURMIDX_1.slurm).
DEFAULT_NUM_SESSIONS = 25
DEFAULT_NUM_FOLDS = 10
DEFAULT_TIME = "48:00:00"
DEFAULT_MEM = "64G"
DEFAULT_CPUS_PER_TASK = 10
DEFAULT_NODES = 1
DEFAULT_NTASKS = 1
DEFAULT_OUTPUT_DIR_REL = "Output_Files"
DEFAULT_ARRAY_THROTTLE = 1  # "%1" — sequential, one task at a time


@dataclass(frozen=True, slots=True)
class SlurmTemplateOptions:
    """Knobs for :func:`render_slurm_template`.

    Most defaults reproduce the MATLAB-side SLURM file structure
    verbatim — only ``sweep_index`` and ``config_name`` are required.
    """

    sweep_index: int
    config_name: str
    num_sessions: int = DEFAULT_NUM_SESSIONS
    num_folds: int = DEFAULT_NUM_FOLDS
    nodes: int = DEFAULT_NODES
    ntasks: int = DEFAULT_NTASKS
    cpus_per_task: int = DEFAULT_CPUS_PER_TASK
    time: str = DEFAULT_TIME
    mem: str = DEFAULT_MEM
    output_dir: str = DEFAULT_OUTPUT_DIR_REL
    array_throttle: int = DEFAULT_ARRAY_THROTTLE
    mail_user: str | None = None       # None = leave blank unless auto-detected
    mail_type: str = "ALL"
    venv_activate: str = "source .venv/bin/activate"
    repo_dir: str | None = None        # None = leave the cd line out
    extra_overrides: tuple[str, ...] = ()


def render_slurm_template(
    options: SlurmTemplateOptions,
    *,
    identity: UserIdentity | None = None,
) -> str:
    """Render a ``.slurm`` script as a string.

    Parameters
    ----------
    options
        :class:`SlurmTemplateOptions` describing the sweep, SLURM
        resources, and Python invocation.
    identity
        Optional pre-computed :class:`~.user_identity.UserIdentity`. When
        omitted, :func:`~.user_identity.identify_user` runs against the
        current process. Threading the identity through is useful in
        tests that need to simulate a different user.

    Returns
    -------
    str
        The full file contents, terminated with a newline.
    """
    entry = _lookup_sweep(options.sweep_index)
    if identity is None:
        identity = identify_user()

    resolved_mail = options.mail_user or maybe_default_mail(identity)
    total_tasks = options.num_sessions * options.num_folds
    array_spec = f"1-{total_tasks}%{options.array_throttle}"

    # Output filename mirrors the MATLAB convention's information density
    # (SLURMChoice + SLURMIDX + array-task) so a Python sweep can be
    # correlated 1:1 with an older MATLAB log just by filename.
    output_template = (
        f"{options.output_dir}/python_sweep-{options.sweep_index}"
        f"-SC{entry.matlab_choice}-IDX{entry.matlab_idx}"
        "-SessionRunIDX-%a.txt"
    )

    # Header comment — explains the differences from the MATLAB .slurm
    # so a reader switching between the two pipelines isn't surprised
    # that %a means SessionRunIDX in Python (it was Fold in MATLAB).
    header_comment_lines = [
        f"# Generated by `python -m neural_data_decoding sweep-emit-slurm`.",
        f"# Sweep entry {options.sweep_index} = MATLAB (SLURMChoice={entry.matlab_choice},"
        f" SLURMIDX={entry.matlab_idx}): {entry.description!r}.",
        f"# Array task ID is SessionRunIDX (1..{total_tasks}, MATLAB ordering:",
        f"# fold-across-sessions). The Python CLI decomposes it into"
        f" (session_idx, fold)",
        f"# at runtime — NumSessions={options.num_sessions},"
        f" NumFolds={options.num_folds}.",
    ]

    sbatch_lines: list[str] = [
        "#!/bin/bash",
        "set -euo pipefail   # fail fast on errors / unset vars / piped command failure",
        "",
        *header_comment_lines,
        "",
    ]
    if resolved_mail:
        sbatch_lines.append(f"#SBATCH --mail-user={resolved_mail}")
        sbatch_lines.append(f"#SBATCH --mail-type={options.mail_type}")
    sbatch_lines.extend([
        f"#SBATCH --nodes={options.nodes}",
        f"#SBATCH --ntasks={options.ntasks}",
        f"#SBATCH --cpus-per-task={options.cpus_per_task}",
        f"#SBATCH --time={options.time}",
        f"#SBATCH --mem={options.mem}",
        f"#SBATCH --array={array_spec}",
        f"#SBATCH --output={output_template}",
    ])
    sbatch_lines.append("")

    info_lines = [
        'echo "SLURM_JOBID: $SLURM_JOBID"',
        'echo "SLURM_ARRAY_TASK_ID: $SLURM_ARRAY_TASK_ID (SessionRunIDX)"',
        'echo "SLURM_ARRAY_JOB_ID: $SLURM_ARRAY_JOB_ID"',
        f'echo "SweepIndex: {options.sweep_index} '
        f'(SC{entry.matlab_choice}/IDX{entry.matlab_idx} = {entry.description})"',
        'echo "Start: $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ]

    env_lines: list[str] = []
    if options.repo_dir:
        env_lines.append(f"cd {options.repo_dir}")
    env_lines.append(options.venv_activate)
    env_lines.append("")

    cmd_parts = [
        "python -m neural_data_decoding train",
        f"    --config-name {options.config_name}",
        f"    --sweep-index {options.sweep_index}",
        "    --session-run-idx $SLURM_ARRAY_TASK_ID",
    ]
    for ov in options.extra_overrides:
        cmd_parts.append(f"    --override {ov}")
    cmd_line = " \\\n".join(cmd_parts)

    body = "\n".join(sbatch_lines + info_lines + env_lines)
    return f"{body}\n{cmd_line}\n"


def write_slurm_template(
    options: SlurmTemplateOptions,
    output_path: Path,
    *,
    identity: UserIdentity | None = None,
) -> Path:
    """Render the template and write it to ``output_path``.

    Creates the parent directory if needed. Returns the absolute path
    of the written file.
    """
    output_path = output_path.expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_slurm_template(options, identity=identity))
    return output_path


__all__ = [
    "DEFAULT_ARRAY_THROTTLE",
    "DEFAULT_CPUS_PER_TASK",
    "DEFAULT_MEM",
    "DEFAULT_NUM_FOLDS",
    "DEFAULT_NUM_SESSIONS",
    "DEFAULT_OUTPUT_DIR_REL",
    "DEFAULT_TIME",
    "SlurmTemplateOptions",
    "render_slurm_template",
    "write_slurm_template",
]
