"""MATLAB-parity tests.

Tests in this directory compare the Python pipeline's output against
reference ``.mat`` files generated by running the MATLAB pipeline on the
same inputs. The references live under ``tests/fixtures/`` and are
**gitignored** — regenerate them locally with ``scripts/prepare_golden_fixtures.py``
(which runs MATLAB in batch mode).

Tests automatically skip when the corresponding reference fixture is
missing, so the suite remains green on fresh checkouts that haven't yet
generated fixtures.
"""
