"""T2 — single-step forward-pass parity for the Simple GRU encoder.

Loads a MATLAB-trained tiny encoder
(``tests/fixtures/golden_weights/encoder_t2_gru_simple.mat`` — generated by
``scripts/generate_t2_encoder_fixture.m``), transplants its weights into a
matching Python :class:`~neural_data_decoding.models.encoder.SimpleSequenceEncoder`,
runs the same input through both, and asserts the per-element error is
within fp32 tolerance.

If the fixture is missing (e.g., a fresh checkout where MATLAB hasn't
been run yet), every test in this module is skipped with a pointer to
the regeneration command.

Tolerance
---------
GRU forward passes accumulate floating-point error across the time
dimension. With identical weights + inputs, MATLAB R2025b and PyTorch
should still match within a few thousand ULPs for the small fixture
(10 timesteps × 2 trials × 2 hidden units). We use atol=1e-5 / rtol=1e-5
— typical for cross-framework single-precision parity. Looser tolerances
would mask real bugs; tighter would flag rounding noise.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import torch

from neural_data_decoding.interop.weight_converter import (
    load_matlab_gru_encoder_weights,
    matlab_cbt_to_pytorch_btc,
    matlab_ctb_to_pytorch_btc,
)
from neural_data_decoding.models.encoder import SimpleSequenceEncoder


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures"
    / "golden_weights"
    / "encoder_t2_gru_simple.mat"
)


# ───────────────────────── Fixture loading ─────────────────────────


@pytest.fixture(scope="module")
def loaded_fixture() -> dict:
    """Load the MATLAB-generated fixture once per module run."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Fixture missing: {FIXTURE_PATH}. "
            "Regenerate with: matlab -batch \"run('scripts/generate_t2_encoder_fixture.m')\""
        )
    raw = scipy.io.loadmat(
        str(FIXTURE_PATH), struct_as_record=False, squeeze_me=False
    )
    return raw


def _scalar(value) -> int:
    """Coerce a scipy-loaded scalar (often a (1,1) array) to a Python int."""
    return int(np.asarray(value).reshape(-1)[0])


@pytest.fixture(scope="module")
def encoder_from_fixture(loaded_fixture: dict) -> SimpleSequenceEncoder:
    """Build a Python encoder matching the fixture's dimensions and load weights."""
    in_features = _scalar(loaded_fixture["in_features"])
    hidden_sizes = np.asarray(loaded_fixture["hidden_sizes"]).reshape(-1).tolist()
    encoder = SimpleSequenceEncoder(
        in_features=in_features,
        hidden_sizes=[int(h) for h in hidden_sizes],
        transform="GRU",
        dropout=0.0,
        want_normalization=False,
        activation="",
    )
    load_matlab_gru_encoder_weights(loaded_fixture, encoder)
    encoder.eval()  # no dropout / no train-mode side effects
    return encoder


# ───────────────────────── Fixture sanity checks ─────────────────────────


def test_fixture_has_expected_layout(loaded_fixture: dict) -> None:
    """The fixture exposes the keys the test relies on."""
    for required in (
        "in_features",
        "hidden_sizes",
        "input",
        "input_format",
        "expected_output",
        "output_format",
        "weights",
    ):
        assert required in loaded_fixture, f"Fixture missing key {required!r}."


def test_fixture_formats_are_ctb_and_cbt(loaded_fixture: dict) -> None:
    """Input is CTB; output is CBT (as observed from the MATLAB script run)."""
    in_fmt = "".join(c for c in str(loaded_fixture["input_format"][0]) if c.isalpha())
    out_fmt = "".join(c for c in str(loaded_fixture["output_format"][0]) if c.isalpha())
    assert in_fmt == "CTB"
    assert out_fmt == "CBT"


# ───────────────────────── Weight-load sanity ─────────────────────────


def test_weights_load_into_encoder_blocks(
    encoder_from_fixture: SimpleSequenceEncoder, loaded_fixture: dict
) -> None:
    """After loading, each block's nn.GRU has the same numbers MATLAB had."""
    weights_struct = loaded_fixture["weights"]
    # scipy gives us a (1, 1) object array wrapping a mat_struct.
    record = weights_struct[0, 0]
    for layer_idx, block in enumerate(encoder_from_fixture.blocks, start=1):
        gru = block.transform_layer
        prefix = f"gru_Encoder_{layer_idx}__"
        ml_input = np.asarray(getattr(record, prefix + "InputWeights"))
        ml_recur = np.asarray(getattr(record, prefix + "RecurrentWeights"))
        ml_bias = np.asarray(getattr(record, prefix + "Bias")).ravel()
        np.testing.assert_allclose(
            gru.weight_ih_l0.detach().numpy(), ml_input, rtol=0, atol=0
        )
        np.testing.assert_allclose(
            gru.weight_hh_l0.detach().numpy(), ml_recur, rtol=0, atol=0
        )
        np.testing.assert_allclose(
            gru.bias_ih_l0.detach().numpy(), ml_bias, rtol=0, atol=0
        )
        np.testing.assert_array_equal(
            gru.bias_hh_l0.detach().numpy(), np.zeros_like(ml_bias)
        )


# ───────────────────────── Forward parity ─────────────────────────


def test_forward_pass_matches_matlab_within_tolerance(
    encoder_from_fixture: SimpleSequenceEncoder, loaded_fixture: dict
) -> None:
    """Python forward output matches MATLAB's predict() to fp32 precision."""
    x_ctb = np.asarray(loaded_fixture["input"], dtype=np.float32)
    expected_cbt = np.asarray(loaded_fixture["expected_output"], dtype=np.float32)

    # Permute MATLAB (C, T, B) → PyTorch (B, T, C).
    x_btc = matlab_ctb_to_pytorch_btc(x_ctb)
    x_torch = torch.from_numpy(x_btc).float()

    with torch.no_grad():
        y_torch = encoder_from_fixture(x_torch).numpy()

    # Permute MATLAB (C, B, T) → (B, T, C) so the shapes align with PyTorch.
    expected_btc = matlab_cbt_to_pytorch_btc(expected_cbt)

    assert y_torch.shape == expected_btc.shape, (
        f"Python output shape {y_torch.shape} does not match the permuted "
        f"MATLAB shape {expected_btc.shape}."
    )

    np.testing.assert_allclose(
        y_torch,
        expected_btc,
        rtol=1e-5,
        atol=1e-5,
        err_msg=(
            "Python encoder forward output does not match MATLAB's "
            "predict() within fp32 tolerance. Maximum absolute diff: "
            f"{np.max(np.abs(y_torch - expected_btc)):.3e}"
        ),
    )


def test_forward_pass_per_layer_intermediate(
    encoder_from_fixture: SimpleSequenceEncoder, loaded_fixture: dict
) -> None:
    """First-block output is well-defined and shape-consistent.

    This is a regression-narrowing test: if the full-stack parity test
    fails, the per-block one localises whether the discrepancy starts at
    block 1 (encoder construction problem) or accumulates only deeper
    (downstream wiring problem). We don't have a MATLAB-side per-block
    output saved, so we just sanity-check shape + finiteness here.
    """
    x_ctb = np.asarray(loaded_fixture["input"], dtype=np.float32)
    x_torch = torch.from_numpy(matlab_ctb_to_pytorch_btc(x_ctb)).float()

    with torch.no_grad():
        block0_out = encoder_from_fixture.blocks[0](x_torch)

    num_trials = _scalar(loaded_fixture["num_trials"])
    num_timesteps = _scalar(loaded_fixture["num_timesteps"])
    h0 = int(np.asarray(loaded_fixture["hidden_sizes"]).reshape(-1)[0])
    assert block0_out.shape == (num_trials, num_timesteps, h0)
    assert torch.isfinite(block0_out).all()
