"""T2 — piecewise-anneal interpolator parity vs ``cgg_calculateDynamicValue``.

Loads ``tests/fixtures/golden_weights/dynamic_schedule_interpolator_t2.mat``
(generated by ``scripts/generate_t2_dynamic_schedule_interpolator_fixture.m``)
and reproduces every per-epoch MATLAB output with
:func:`piecewise_anneal_value`.

The fixture covers six cases — basic 2-waypoint ramps (increasing,
decreasing, wide), a 3-waypoint schedule that exhibits the
``(epoch - 1)`` off-by-one discontinuity at internal waypoints, a single
waypoint (left/right clamp edge), and the full Soft Three-Stage
Curriculum - Shortened regime (every parameter across all 50 epochs).

If any test ever drifts from ~1e-12, the interpolator port has lost MATLAB
parity — most likely a regression on the off-by-one quirk inside
``cgg_annealWeight``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pytest
import scipy.io

from neural_data_decoding.training.schedules import piecewise_anneal_value


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures" / "golden_weights" / "dynamic_schedule_interpolator_t2.mat"
)


@pytest.fixture(scope="module")
def fixture() -> dict:
    """Load the interpolator T2 fixture once per module run."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Interpolator fixture missing: {FIXTURE_PATH}. Regenerate with: "
            "matlab -batch \"run('scripts/generate_t2_dynamic_schedule_interpolator_fixture.m')\""
        )
    return scipy.io.loadmat(str(FIXTURE_PATH), struct_as_record=False, squeeze_me=False)


def _unwrap(struct_field: Any) -> Any:
    """Unwrap a MATLAB struct array into its single scalar struct.

    Returns ``Any`` because scipy.io's loaded structs are dynamic; field
    access on them is name-driven and cannot be statically typed.
    """
    return struct_field[0, 0]


def _vec(arr: Any) -> np.ndarray:
    """Coerce a MATLAB row-vector field into a 1-D numpy array."""
    return np.asarray(arr, dtype=np.float64).reshape(-1)


def _scalar(arr: Any) -> float:
    return float(np.asarray(arr).reshape(-1)[0])


def _python_values(
    base: float, epoch_points: Any, magnitude_points: Any, epochs: Any,
) -> np.ndarray:
    """Compute python-side values for a vector of epochs."""
    eps = _vec(epoch_points).tolist()
    mags = _vec(magnitude_points).tolist()
    es = _vec(epochs).astype(int).tolist()
    return np.asarray(
        [piecewise_anneal_value(base, eps, mags, e) for e in es],
        dtype=np.float64,
    )


def _assert_per_epoch_parity(case: Any, *, name: str) -> None:
    """Assert per-epoch parity for a simple (base, epoch_points, magnitudes) case."""
    base = _scalar(case.base)
    py = _python_values(base, case.epoch_points, case.magnitude_points, case.epochs)
    matlab = _vec(case.values)
    np.testing.assert_allclose(
        py, matlab, rtol=1e-12, atol=1e-12,
        err_msg=f"{name}: per-epoch values differ from MATLAB",
    )


# ───────────────────────── Cases A, B, E, F: 2- and 1-waypoint cases ─────────────────────────


def test_case_A_increasing_two_waypoint(fixture: dict) -> None:
    """Increasing ramp [0.1 → 1.0] over [10, 20]; covers basic clamps + linear ramp."""
    _assert_per_epoch_parity(_unwrap(fixture["case_A"]), name="case_A")


def test_case_B_decreasing_two_waypoint_with_nontrivial_base(fixture: dict) -> None:
    """Decreasing ramp [1.0 → 1e-2] over [20, 30] with base=2.0; verifies multiplication."""
    _assert_per_epoch_parity(_unwrap(fixture["case_B"]), name="case_B")


def test_case_E_single_waypoint(fixture: dict) -> None:
    """Single waypoint at epoch 10 (magnitude 0.5); left- and right-clamp only."""
    _assert_per_epoch_parity(_unwrap(fixture["case_E"]), name="case_E")


def test_case_F_wide_segment_linear_ramp(fixture: dict) -> None:
    """Wide [10, 40] ramp [0 → 1]; many in-segment epochs to expose the linear slope."""
    _assert_per_epoch_parity(_unwrap(fixture["case_F"]), name="case_F")


# ───────────────────────── Case C: 3-waypoint inner-discontinuity probe ─────────────────────────


def test_case_C_three_waypoint_internal_discontinuity(fixture: dict) -> None:
    """3-waypoint [1e-2, 1e-2, 1.0] over [0, 50, 75].

    The constant first segment + ramping second segment exposes the
    ``(epoch - 1)`` off-by-one at the internal waypoint epoch=50: the
    ramp begins at epoch=51 (value = 1e-2), and at epoch=75 (the last
    in-segment epoch) the value is ``1e-2 + (1.0 - 1e-2) * 24/25`` —
    NOT exactly 1.0. At epoch=76 the right-clamp snaps to 1.0.
    """
    _assert_per_epoch_parity(_unwrap(fixture["case_C"]), name="case_C")


def test_case_C_off_by_one_quirk_is_preserved(fixture: dict) -> None:
    """Pin the specific discontinuity values, not just per-epoch parity.

    This guards against a "well-meaning" refactor that 'fixes' the
    off-by-one and breaks MATLAB parity.
    """
    C = _unwrap(fixture["case_C"])
    values = _vec(C.values)
    epochs = _vec(C.epochs).astype(int)

    epoch_to_value = dict(zip(epochs.tolist(), values.tolist()))

    # Constant-first-segment region: every epoch ≤ 50 is exactly 1e-2.
    assert epoch_to_value[50] == pytest.approx(1e-2, rel=1e-12, abs=1e-12)
    assert epoch_to_value[1]  == pytest.approx(1e-2, rel=1e-12, abs=1e-12)

    # First in-ramp epoch: epoch=51 → ramp position 0, still at MinWeight=1e-2.
    assert epoch_to_value[51] == pytest.approx(1e-2, rel=1e-12, abs=1e-12)

    # Second in-ramp epoch: epoch=52 → ramp = 1 * (0.99 / 25) = 0.0396.
    expected_52 = 1e-2 + (1.0 - 1e-2) * (1.0 / 25.0)
    assert epoch_to_value[52] == pytest.approx(expected_52, rel=1e-12, abs=1e-12)

    # Last in-segment epoch (epoch=75): ramp = 24 * (0.99 / 25) — does NOT reach 1.0.
    expected_75 = 1e-2 + (1.0 - 1e-2) * (24.0 / 25.0)
    assert epoch_to_value[75] == pytest.approx(expected_75, rel=1e-12, abs=1e-12)
    # The discontinuity: epoch=76 right-clamps to MagnitudePoints[-1] = 1.0.
    assert epoch_to_value[76] == pytest.approx(1.0, rel=1e-12, abs=1e-12)


# ───────────────────────── Case D: real Soft Three-Stage Curriculum - Shortened ─────────────────────────


def _per_param_parity(
    epoch_points: Any,
    magnitude_points: Any,
    values: Any,
    epochs: Any,
    *,
    param_name: str,
) -> None:
    py = _python_values(1.0, epoch_points, magnitude_points, epochs)
    matlab = _vec(values)
    np.testing.assert_allclose(
        py, matlab, rtol=1e-12, atol=1e-12,
        err_msg=f"case_D[{param_name}]: per-epoch values differ from MATLAB",
    )


@pytest.mark.parametrize(
    "param", ["Classification", "Confidence", "Reconstruction", "KL"],
)
def test_case_D_weight_schedule_parameter(fixture: dict, param: str) -> None:
    """Every weight parameter in the Soft Three-Stage regime matches over all 50 epochs."""
    D = _unwrap(fixture["case_D"])
    weights_struct = _unwrap(D.dynamic_weighting)
    weight_vals = _unwrap(D.weight_values_base1)
    param_schedule = _unwrap(getattr(weights_struct, param))
    _per_param_parity(
        param_schedule.EpochPoints,
        param_schedule.MagnitudePoints,
        getattr(weight_vals, param),
        D.epochs,
        param_name=f"weights.{param}",
    )


@pytest.mark.parametrize("network", ["Encoder", "Decoder", "Classifier"])
def test_case_D_freeze_schedule_parameter(fixture: dict, network: str) -> None:
    """Every freeze-factor parameter matches over all 50 epochs."""
    D = _unwrap(fixture["case_D"])
    freeze_struct = _unwrap(D.dynamic_freezing)
    freeze_vals = _unwrap(D.freeze_values_base1)
    network_schedule = _unwrap(getattr(freeze_struct, network))
    _per_param_parity(
        network_schedule.EpochPoints,
        network_schedule.MagnitudePoints,
        getattr(freeze_vals, network),
        D.epochs,
        param_name=f"freeze.{network}",
    )


def test_case_D_augmentation_shared_schedule(fixture: dict) -> None:
    """The flat augmentation schedule (shared across all augmentation params) matches."""
    D = _unwrap(fixture["case_D"])
    _per_param_parity(
        D.aug_epoch_points,
        D.aug_magnitude_points,
        D.aug_values_base1,
        D.epochs,
        param_name="augmentation (shared)",
    )
