"""T2 — MIL-pooling parity: multi-axis softmax vs ``cgg_softmaxLayer``.

Loads ``tests/fixtures/golden_weights/mil_softmax_t2.mat`` (generated by
``scripts/generate_t2_mil_softmax_fixture.m``) and reproduces every MATLAB
output with :class:`~neural_data_decoding.models.layers.mil_softmax.MILSoftmaxLayer`.

The fixture exercises three layouts, pinning the
``find(ismember(dims(X), SoftmaxFormat))`` axis mapping (Critical Note #10:
MIL pooling is a joint softmax across Space-Channel-Time):

* ``CBT`` / ``'SCT'``   → joint softmax over channel + time   (numpy axes 0, 2)
* ``CBT`` / ``'C'``     → softmax over channel only           (numpy axis 0)
* ``SSCTB`` / ``'SCT'`` → joint softmax over space+chan+time  (numpy axes 0,1,2,3)

Both the saved inputs and outputs are in their construction layout (the
generator undoes MATLAB's canonical dlarray reshuffle), so each output is a
direct elementwise comparison. Skips cleanly when the fixture is absent.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import torch

from neural_data_decoding.models.layers.mil_softmax import MILSoftmaxLayer


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures"
    / "golden_weights"
    / "mil_softmax_t2.mat"
)


@pytest.fixture(scope="module")
def fixture() -> dict:
    """Load the MIL-softmax fixture once per module run."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"MIL-softmax fixture missing: {FIXTURE_PATH}. Regenerate with: "
            "matlab -batch \"run('scripts/generate_t2_mil_softmax_fixture.m')\""
        )
    return scipy.io.loadmat(str(FIXTURE_PATH))


def test_cbt_sct_matches_matlab(fixture: dict) -> None:
    """CBT input, 'SCT' format → joint softmax over channel + time (axes 0, 2)."""
    x = torch.from_numpy(np.asarray(fixture["X_cbt"], dtype=np.float64))
    layer = MILSoftmaxLayer.from_formats(softmax_format="SCT", tensor_format="CBT")
    assert layer.dims == (0, 2)
    z = layer(x).numpy()
    np.testing.assert_allclose(
        z, np.asarray(fixture["Z_cbt_sct"], dtype=np.float64), rtol=1e-6, atol=1e-6
    )


def test_cbt_channel_only_matches_matlab(fixture: dict) -> None:
    """CBT input, 'C' format → softmax over channel only (axis 0)."""
    x = torch.from_numpy(np.asarray(fixture["X_cbt"], dtype=np.float64))
    layer = MILSoftmaxLayer.from_formats(softmax_format="C", tensor_format="CBT")
    assert layer.dims == (0,)
    z = layer(x).numpy()
    np.testing.assert_allclose(
        z, np.asarray(fixture["Z_cbt_c"], dtype=np.float64), rtol=1e-6, atol=1e-6
    )


def test_ssctb_sct_matches_matlab(fixture: dict) -> None:
    """SSCTB input, 'SCT' → joint softmax over space+channel+time (axes 0,1,2,3)."""
    x = torch.from_numpy(np.asarray(fixture["X_ssctb"], dtype=np.float64))
    layer = MILSoftmaxLayer.from_formats(
        softmax_format="SCT", tensor_format="SSCTB"
    )
    assert layer.dims == (0, 1, 2, 3)
    z = layer(x).numpy()
    np.testing.assert_allclose(
        z, np.asarray(fixture["Z_ssctb_sct"], dtype=np.float64), rtol=1e-6, atol=1e-6
    )
