"""T2 — confidence-routing parity vs ``cgg_lossConfidence`` (Critical Note #29).

Loads ``tests/fixtures/golden_weights/confidence_t2.mat`` (generated by
``scripts/generate_t2_confidence_fixture.m``) and reproduces every MATLAB
output with :func:`apply_confidence_routing`. Each subtlety has its own
test so a regression localizes to the specific math that drifted.

Subtleties exercised
--------------------

* **Case A** — Conjunction (#1) + Interpolation (#3): asserts ``Y'``,
  ``loss_Total``, ``loss_Trial``, ``loss_Task`` all match. Dropout
  disabled (``confidence_dropout=1.0``) to isolate the deterministic math.
* **Cases B (γ ∈ {0.1, 0.5, 1.0})** — EMA cadence (#5): asserts the
  updated EMA value AND the resulting Trial-branch loss for each γ.
* **Case C** — Batch correction (Eq. 10): asserts
  ``loss_corrected / loss_raw == 1/γ``.
* **Case D** — Conjunction analytically: pins
  ``loss_Total = |mean(Task * Trial) - 1|``.

Dropout-mask behavior (#2) and stop-gradient on history (#4) are unit-
tested in :mod:`tests.unit.test_confidence` — they're deterministic /
autograd-internal, no MATLAB fixture needed.

The MATLAB fixture uses dlarray format ``'CBT'`` (channel, batch, time).
scipy.io.loadmat preserves the shape, so MATLAB ``(C, B, T)`` arrives as
numpy ``(C, B, T)``. The kernel expects ``(B, T, C)``, so each tensor is
permuted ``(1, 2, 0)`` before being passed in.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import torch

from neural_data_decoding.training.losses.confidence import (
    ConfidenceHistory,
    apply_confidence_routing,
)


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures" / "golden_weights" / "confidence_t2.mat"
)


def _scalar(v) -> float:
    return float(np.asarray(v).reshape(-1)[0])


def _cbt_to_btc(x: np.ndarray) -> np.ndarray:
    """Permute a MATLAB CBT-laid-out array to PyTorch's (B, T, C)."""
    return np.transpose(x, (1, 2, 0))


@pytest.fixture(scope="module")
def fixture() -> dict:
    """Load the confidence T2 fixture once per module run."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Confidence fixture missing: {FIXTURE_PATH}. Regenerate with: "
            "matlab -batch \"run('scripts/generate_t2_confidence_fixture.m')\""
        )
    return scipy.io.loadmat(str(FIXTURE_PATH), struct_as_record=False, squeeze_me=False)


def _case(fixture: dict, name: str):
    """Pick a sub-struct case (case_A, case_C, case_D, or one from cases_B)."""
    return fixture[name][0, 0]


# ───────────────────────── Case A: conjunction + interpolation ─────────────────────────


def test_case_A_conjunction_and_interpolation(fixture: dict) -> None:
    """All three losses + Y' match MATLAB for dropout-disabled conjunction case."""
    A = _case(fixture, "case_A")
    y      = torch.from_numpy(_cbt_to_btc(np.asarray(A.Y_in,         dtype=np.float64)))
    target = torch.from_numpy(_cbt_to_btc(np.asarray(A.T_in,         dtype=np.float64)))
    trial  = torch.from_numpy(_cbt_to_btc(np.asarray(A.TrialConf_in, dtype=np.float64)))
    task   = torch.from_numpy(_cbt_to_btc(np.asarray(A.TaskConf_in,  dtype=np.float64)))

    out = apply_confidence_routing(
        y, target, trial, task,
        history=ConfidenceHistory.initial(dtype=torch.float64),
        batch_fraction=1.0,
        confidence_dropout=1.0,        # mask always False → dropped == undropped
        want_dataset_confidence=False,
        loss_type="L1",
    )

    np.testing.assert_allclose(
        float(out.total_loss), _scalar(A.loss_Total), rtol=1e-10, atol=1e-10
    )
    np.testing.assert_allclose(
        float(out.trial_loss), _scalar(A.loss_Trial), rtol=1e-10, atol=1e-10
    )
    np.testing.assert_allclose(
        float(out.task_loss),  _scalar(A.loss_Task),  rtol=1e-10, atol=1e-10
    )
    # Y_out from MATLAB is CBT; permute to BTC and compare elementwise.
    y_out_matlab = torch.from_numpy(_cbt_to_btc(np.asarray(A.Y_out, dtype=np.float64)))
    np.testing.assert_allclose(
        out.y_interpolated.numpy(), y_out_matlab.numpy(), rtol=1e-10, atol=1e-10
    )


# ───────────────────────── Case B: BatchFraction EMA cadence ─────────────────────────


@pytest.mark.parametrize("gamma_key", ["gamma_010", "gamma_050", "gamma_100"])
def test_case_B_batch_fraction_ema(fixture: dict, gamma_key: str) -> None:
    """For each γ, updated EMA and the Trial-branch loss match MATLAB."""
    cases_B = fixture["cases_B"][0, 0]
    B = getattr(cases_B, gamma_key)[0, 0]
    gamma = _scalar(B.gamma)

    A = _case(fixture, "case_A")  # reuse the same trial inputs
    y      = torch.from_numpy(_cbt_to_btc(np.asarray(A.Y_in,         dtype=np.float64)))
    target = torch.from_numpy(_cbt_to_btc(np.asarray(A.T_in,         dtype=np.float64)))
    trial  = torch.from_numpy(_cbt_to_btc(np.asarray(A.TrialConf_in, dtype=np.float64)))
    task   = torch.from_numpy(_cbt_to_btc(np.asarray(A.TaskConf_in,  dtype=np.float64)))

    hist_init = _scalar(fixture["hist_init"])
    history = ConfidenceHistory.initial(dtype=torch.float64, value=hist_init)

    out = apply_confidence_routing(
        y, target, trial, task,
        history=history,
        batch_fraction=gamma,
        confidence_dropout=1.0,
        want_dataset_confidence=True,
        loss_type="L1",
    )

    np.testing.assert_allclose(
        float(out.trial_loss), _scalar(B.loss_Trial), rtol=1e-10, atol=1e-10,
        err_msg=f"loss_Trial mismatch at γ={gamma}",
    )
    np.testing.assert_allclose(
        float(out.updated_history.trial), _scalar(B.updated_ema),
        rtol=1e-10, atol=1e-10,
        err_msg=f"updated EMA mismatch at γ={gamma}",
    )


# ───────────────────────── Case C: batch correction (Eq. 10) ─────────────────────────


def test_case_C_batch_correction_scales_by_one_over_gamma(fixture: dict) -> None:
    """``loss_corrected / loss_raw == 1/γ`` (matches MATLAB to 1e-10)."""
    C = _case(fixture, "case_C")
    gamma = _scalar(C.gamma)
    A = _case(fixture, "case_A")
    y      = torch.from_numpy(_cbt_to_btc(np.asarray(A.Y_in,         dtype=np.float64)))
    target = torch.from_numpy(_cbt_to_btc(np.asarray(A.T_in,         dtype=np.float64)))
    trial  = torch.from_numpy(_cbt_to_btc(np.asarray(A.TrialConf_in, dtype=np.float64)))
    task   = torch.from_numpy(_cbt_to_btc(np.asarray(A.TaskConf_in,  dtype=np.float64)))

    hist_init = _scalar(fixture["hist_init"])

    def _run(*, want_correction: bool):
        return apply_confidence_routing(
            y, target, trial, task,
            history=ConfidenceHistory.initial(dtype=torch.float64, value=hist_init),
            batch_fraction=gamma,
            confidence_dropout=1.0,
            want_dataset_confidence=True,
            want_batch_correction=want_correction,
            loss_type="L1",
        )

    raw  = _run(want_correction=False)
    corr = _run(want_correction=True)

    np.testing.assert_allclose(
        float(raw.trial_loss),  _scalar(C.loss_Trial_noCorr), rtol=1e-10, atol=1e-10
    )
    np.testing.assert_allclose(
        float(corr.trial_loss), _scalar(C.loss_Trial_corr),   rtol=1e-10, atol=1e-10
    )
    np.testing.assert_allclose(
        float(corr.trial_loss) / float(raw.trial_loss), 1.0 / gamma,
        rtol=1e-10, atol=1e-10,
        err_msg="Batch correction did not scale by 1/γ",
    )


# ───────────────────────── Case D: conjunction analytical ─────────────────────────


def test_case_D_conjunction_total_mean_analytical(fixture: dict) -> None:
    """``mean(Task_last * Trial_last)`` matches MATLAB's analytical value."""
    D = _case(fixture, "case_D")
    A = _case(fixture, "case_A")
    trial = torch.from_numpy(_cbt_to_btc(np.asarray(A.TrialConf_in, dtype=np.float64)))
    task  = torch.from_numpy(_cbt_to_btc(np.asarray(A.TaskConf_in,  dtype=np.float64)))

    # Take last timestep along time_dim=1; multiply; check the mean.
    trial_last = trial.select(1, trial.shape[1] - 1)
    task_last  = task.select(1,  task.shape[1] - 1)
    total      = trial_last * task_last
    py_mean    = float(total.mean())
    np.testing.assert_allclose(
        py_mean, _scalar(D.total_mean_expected), rtol=1e-10, atol=1e-10
    )
    # Loss_Total (analytical) = |mean - 1| for L1 with target=1.
    py_loss_total = abs(py_mean - 1.0)
    np.testing.assert_allclose(
        py_loss_total, _scalar(D.loss_total_analytical), rtol=1e-10, atol=1e-10
    )
