"""T2 — single-step forward-pass parity for the Simple GRU encoder.

Loads a MATLAB-trained tiny encoder
(``tests/fixtures/golden_weights/encoder_t2_gru_simple.mat`` — generated by
``scripts/generate_t2_encoder_fixture.m``), transplants its weights into a
matching Python :class:`~neural_data_decoding.models.encoder.SimpleSequenceEncoder`,
runs the same input through both, and asserts the per-element error is
within fp32 tolerance.

If the fixture is missing (e.g., a fresh checkout where MATLAB hasn't
been run yet), every test in this module is skipped with a pointer to
the regeneration command.

Tolerance
---------
GRU forward passes accumulate floating-point error across the time
dimension. With identical weights + inputs, MATLAB R2025b and PyTorch
should still match within a few thousand ULPs for the small fixture
(10 timesteps × 2 trials × 2 hidden units). We use atol=1e-5 / rtol=1e-5
— typical for cross-framework single-precision parity. Looser tolerances
would mask real bugs; tighter would flag rounding noise.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import torch

from neural_data_decoding.interop.weight_converter import (
    load_matlab_gru_encoder_weights,
    load_matlab_lstm_encoder_weights,
    matlab_cbt_to_pytorch_btc,
    matlab_ctb_to_pytorch_btc,
)
from neural_data_decoding.models.encoder import SimpleSequenceEncoder


FIXTURE_DIR = (
    Path(__file__).resolve().parent.parent / "fixtures" / "golden_weights"
)
FIXTURE_PATH = FIXTURE_DIR / "encoder_t2_gru_simple.mat"
LSTM_FIXTURE_PATH = FIXTURE_DIR / "encoder_t2_lstm_simple.mat"


_TRANSFORM_SPEC = {
    "GRU": (FIXTURE_PATH, load_matlab_gru_encoder_weights, "gru_Encoder_"),
    "LSTM": (LSTM_FIXTURE_PATH, load_matlab_lstm_encoder_weights, "lstm_Encoder_"),
}


# ───────────────────────── Fixture loading ─────────────────────────


def _scalar(value) -> int:
    """Coerce a scipy-loaded scalar (often a (1,1) array) to a Python int."""
    return int(np.asarray(value).reshape(-1)[0])


def _load_fixture(transform: str) -> dict:
    path, _, _ = _TRANSFORM_SPEC[transform]
    if not path.exists():
        script_name = (
            "generate_t2_encoder_fixture.m"
            if transform == "GRU"
            else "generate_t2_encoder_fixture_lstm.m"
        )
        pytest.skip(
            f"{transform} fixture missing: {path}. "
            f"Regenerate with: matlab -batch \"run('scripts/{script_name}')\""
        )
    return scipy.io.loadmat(
        str(path), struct_as_record=False, squeeze_me=False
    )


def _build_encoder_from_fixture(
    fixture: dict, transform: str
) -> SimpleSequenceEncoder:
    in_features = _scalar(fixture["in_features"])
    hidden_sizes = np.asarray(fixture["hidden_sizes"]).reshape(-1).tolist()
    encoder = SimpleSequenceEncoder(
        in_features=in_features,
        hidden_sizes=[int(h) for h in hidden_sizes],
        transform=transform,
        dropout=0.0,
        want_normalization=False,
        activation="",
    )
    _, loader, _ = _TRANSFORM_SPEC[transform]
    loader(fixture, encoder)
    encoder.eval()
    return encoder


@pytest.fixture(scope="module", params=list(_TRANSFORM_SPEC.keys()))
def transform(request: pytest.FixtureRequest) -> str:
    """Run the whole module against each transform (GRU, LSTM)."""
    return request.param


@pytest.fixture(scope="module")
def loaded_fixture(transform: str) -> dict:
    """Load the MATLAB-generated fixture for the active transform."""
    return _load_fixture(transform)


@pytest.fixture(scope="module")
def encoder_from_fixture(
    loaded_fixture: dict, transform: str
) -> SimpleSequenceEncoder:
    """Build a Python encoder matching the fixture and load weights."""
    return _build_encoder_from_fixture(loaded_fixture, transform)


# ───────────────────────── Fixture sanity checks ─────────────────────────


def test_fixture_has_expected_layout(loaded_fixture: dict) -> None:
    """The fixture exposes the keys the test relies on."""
    for required in (
        "in_features",
        "hidden_sizes",
        "input",
        "input_format",
        "expected_output",
        "output_format",
        "weights",
    ):
        assert required in loaded_fixture, f"Fixture missing key {required!r}."


def test_fixture_formats_are_ctb_and_cbt(loaded_fixture: dict) -> None:
    """Input is CTB; output is CBT (as observed from MATLAB)."""
    in_fmt = "".join(c for c in str(loaded_fixture["input_format"][0]) if c.isalpha())
    out_fmt = "".join(c for c in str(loaded_fixture["output_format"][0]) if c.isalpha())
    assert in_fmt == "CTB"
    assert out_fmt == "CBT"


# ───────────────────────── Weight-load sanity ─────────────────────────


def test_weights_load_into_encoder_blocks(
    encoder_from_fixture: SimpleSequenceEncoder,
    loaded_fixture: dict,
    transform: str,
) -> None:
    """Each block's RNN module has the same numbers MATLAB had."""
    weights_struct = loaded_fixture["weights"]
    record = weights_struct[0, 0]
    _, _, prefix_base = _TRANSFORM_SPEC[transform]
    for layer_idx, block in enumerate(encoder_from_fixture.blocks, start=1):
        rnn = block.transform_layer
        prefix = f"{prefix_base}{layer_idx}__"
        ml_input = np.asarray(getattr(record, prefix + "InputWeights"))
        ml_recur = np.asarray(getattr(record, prefix + "RecurrentWeights"))
        ml_bias = np.asarray(getattr(record, prefix + "Bias")).ravel()
        np.testing.assert_allclose(
            rnn.weight_ih_l0.detach().numpy(), ml_input, rtol=0, atol=0
        )
        np.testing.assert_allclose(
            rnn.weight_hh_l0.detach().numpy(), ml_recur, rtol=0, atol=0
        )
        np.testing.assert_allclose(
            rnn.bias_ih_l0.detach().numpy(), ml_bias, rtol=0, atol=0
        )
        np.testing.assert_array_equal(
            rnn.bias_hh_l0.detach().numpy(), np.zeros_like(ml_bias)
        )


# ───────────────────────── Forward parity ─────────────────────────


def test_forward_pass_matches_matlab_within_tolerance(
    encoder_from_fixture: SimpleSequenceEncoder,
    loaded_fixture: dict,
) -> None:
    """Python forward output matches MATLAB's predict() to fp32 precision."""
    x_ctb = np.asarray(loaded_fixture["input"], dtype=np.float32)
    expected_cbt = np.asarray(loaded_fixture["expected_output"], dtype=np.float32)

    x_btc = matlab_ctb_to_pytorch_btc(x_ctb)
    x_torch = torch.from_numpy(x_btc).float()

    with torch.no_grad():
        y_torch = encoder_from_fixture(x_torch).numpy()

    expected_btc = matlab_cbt_to_pytorch_btc(expected_cbt)
    assert y_torch.shape == expected_btc.shape

    np.testing.assert_allclose(
        y_torch,
        expected_btc,
        rtol=1e-5,
        atol=1e-5,
        err_msg=(
            "Python encoder forward output does not match MATLAB's "
            "predict() within fp32 tolerance. Maximum absolute diff: "
            f"{np.max(np.abs(y_torch - expected_btc)):.3e}"
        ),
    )


def test_forward_pass_per_layer_intermediate(
    encoder_from_fixture: SimpleSequenceEncoder, loaded_fixture: dict
) -> None:
    """First-block output has the right shape and is finite."""
    x_ctb = np.asarray(loaded_fixture["input"], dtype=np.float32)
    x_torch = torch.from_numpy(matlab_ctb_to_pytorch_btc(x_ctb)).float()

    with torch.no_grad():
        block0_out = encoder_from_fixture.blocks[0](x_torch)

    num_trials = _scalar(loaded_fixture["num_trials"])
    num_timesteps = _scalar(loaded_fixture["num_timesteps"])
    h0 = int(np.asarray(loaded_fixture["hidden_sizes"]).reshape(-1)[0])
    assert block0_out.shape == (num_trials, num_timesteps, h0)
    assert torch.isfinite(block0_out).all()
