"""T2 — Curriculum YAML preset parity vs MATLAB regime structs.

Loads ``configs/schedule/soft_three_stage_curriculum_shortened.yaml`` and
verifies every per-epoch value matches MATLAB's
``PARAMETERS_cgg_selectDynamicParameters('Soft Three-Stage Curriculum - Shortened')``
across all 50 epochs and every parameter (weights, freeze, augmentation).

The fixture reused here is ``dynamic_schedule_interpolator_t2.mat`` —
its ``case_D`` block already captures the MATLAB regime's per-parameter
per-epoch values with base=1.0, generated by running the MATLAB
``PARAMETERS_cgg_selectDynamicParameters`` function inside the fixture
script. This avoids a second MATLAB round-trip.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pytest
import scipy.io

from neural_data_decoding.training.schedules import (
    CurriculumBundle,
    load_curriculum_by_name,
)


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures" / "golden_weights" / "dynamic_schedule_interpolator_t2.mat"
)


@pytest.fixture(scope="module")
def case_D() -> Any:
    """Load the case_D sub-struct (real Soft Three-Stage regime)."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Interpolator fixture missing: {FIXTURE_PATH}. Regenerate with: "
            "matlab -batch \"run('scripts/generate_t2_dynamic_schedule_interpolator_fixture.m')\""
        )
    raw = scipy.io.loadmat(str(FIXTURE_PATH), struct_as_record=False, squeeze_me=False)
    return raw["case_D"][0, 0]


@pytest.fixture(scope="module")
def bundle() -> CurriculumBundle:
    """Load the Soft Three-Stage Curriculum - Shortened preset by MATLAB name.

    Bases are all 1.0 so the per-epoch values are directly comparable to
    the MATLAB-side ``case_D.*_values_base1`` arrays.
    """
    return load_curriculum_by_name(
        "Soft Three-Stage Curriculum - Shortened",
        base_loads={
            "std_channel_offset": 1.0,
            "std_white_noise": 1.0,
            "std_random_walk": 1.0,
            "std_time_shift": 1.0,
        },
        base_weights={
            "reconstruction": 1.0,
            "kl": 1.0,
            "classification": 1.0,
            "confidence": 1.0,
            "offset_and_scale": 1.0,
        },
        base_freezes={"encoder": 1.0, "decoder": 1.0, "classifier": 1.0},
    )


def _vec(arr: Any) -> np.ndarray:
    return np.asarray(arr, dtype=np.float64).reshape(-1)


def _trace(bundle: CurriculumBundle, schedule_name: str, param_name: str, epochs) -> np.ndarray:
    """Run the bundle through every epoch and record one parameter's current value."""
    schedule = getattr(bundle, schedule_name)
    out: list[float] = []
    for e in epochs:
        bundle.update(int(e))
        out.append(schedule.current(param_name))
    return np.asarray(out, dtype=np.float64)


# ───────────────────────── Weight schedule parity ─────────────────────────


@pytest.mark.parametrize(
    "matlab_name,python_name",
    [
        ("Classification",  "classification"),
        ("Confidence",      "confidence"),
        ("Reconstruction",  "reconstruction"),
        ("KL",              "kl"),
    ],
)
def test_weight_parameter_matches_matlab_regime(
    case_D: Any, bundle: CurriculumBundle, matlab_name: str, python_name: str,
) -> None:
    """Every weight parameter's per-epoch values match the MATLAB regime."""
    epochs = _vec(case_D.epochs).astype(int)
    matlab_vals = _vec(getattr(case_D.weight_values_base1[0, 0], matlab_name))
    py_vals = _trace(bundle, "weight", python_name, epochs)
    np.testing.assert_allclose(
        py_vals, matlab_vals, rtol=1e-12, atol=1e-12,
        err_msg=f"weights.{python_name} drifted from MATLAB regime",
    )


# ───────────────────────── Freeze schedule parity ─────────────────────────


@pytest.mark.parametrize(
    "matlab_name,python_name",
    [
        ("Encoder",    "encoder"),
        ("Decoder",    "decoder"),
        ("Classifier", "classifier"),
    ],
)
def test_freeze_parameter_matches_matlab_regime(
    case_D: Any, bundle: CurriculumBundle, matlab_name: str, python_name: str,
) -> None:
    """Every freeze-factor parameter's per-epoch values match the MATLAB regime."""
    epochs = _vec(case_D.epochs).astype(int)
    matlab_vals = _vec(getattr(case_D.freeze_values_base1[0, 0], matlab_name))
    py_vals = _trace(bundle, "freeze", python_name, epochs)
    np.testing.assert_allclose(
        py_vals, matlab_vals, rtol=1e-12, atol=1e-12,
        err_msg=f"freeze.{python_name} drifted from MATLAB regime",
    )


# ───────────────────────── Augmentation (shared) parity ─────────────────────────


def test_augmentation_shared_schedule_applies_to_every_std(
    case_D: Any, bundle: CurriculumBundle,
) -> None:
    """The flat augmentation schedule applies identically to every std_* parameter."""
    epochs = _vec(case_D.epochs).astype(int)
    matlab_vals = _vec(case_D.aug_values_base1)
    for name in ("std_channel_offset", "std_white_noise",
                 "std_random_walk", "std_time_shift"):
        py_vals = _trace(bundle, "load", name, epochs)
        np.testing.assert_allclose(
            py_vals, matlab_vals, rtol=1e-12, atol=1e-12,
            err_msg=f"load.{name} drifted from MATLAB augmentation schedule",
        )
