"""T2 — single-step forward parity for the full Milestone B composite.

Loads a MATLAB-built GRU-encoder + FC-bottleneck + Deep-LSTM-classifier
chain (``tests/fixtures/golden_weights/composite_t2_gru_deeplstm.mat``,
generated by ``scripts/generate_t2_composite_fixture.m``), transplants
every weight into an
:class:`~neural_data_decoding.models.composite.EncoderClassifierComposite`,
and asserts the per-dimension pre-softmax logits match MATLAB within fp32
tolerance.

This closes the Milestone B single-step parity gate: the encoder-only
test proved the RNN math; this one adds the FC bottleneck, the per-dim
Deep-LSTM classifier trunks, and the end-to-end wiring.

The fixture is gitignored (golden weights are regenerated locally). When
it is absent, every test here skips with a regeneration hint.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import torch

from neural_data_decoding.interop.weight_converter import (
    load_matlab_composite_weights,
    matlab_cbt_to_pytorch_btc,
    matlab_ctb_to_pytorch_btc,
)
from neural_data_decoding.models.bottleneck import LinearBottleneck
from neural_data_decoding.models.classifier import DeepLSTMClassifier
from neural_data_decoding.models.composite import EncoderClassifierComposite
from neural_data_decoding.models.encoder import SimpleSequenceEncoder


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures"
    / "golden_weights"
    / "composite_t2_gru_deeplstm.mat"
)


def _scalar(value) -> int:
    return int(np.asarray(value).reshape(-1)[0])


def _int_list(value) -> list[int]:
    return [int(v) for v in np.asarray(value).reshape(-1).tolist()]


@pytest.fixture(scope="module")
def fixture() -> dict:
    """Load the composite fixture once per module run."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Composite fixture missing: {FIXTURE_PATH}. Regenerate with: "
            "matlab -batch \"run('scripts/generate_t2_composite_fixture.m')\""
        )
    return scipy.io.loadmat(
        str(FIXTURE_PATH), struct_as_record=False, squeeze_me=False
    )


@pytest.fixture(scope="module")
def composite(fixture: dict) -> EncoderClassifierComposite:
    """Build a composite matching the fixture and transplant all weights."""
    in_features = _scalar(fixture["in_features"])
    hidden_sizes = _int_list(fixture["hidden_sizes"])
    bottleneck_size = _scalar(fixture["bottleneck_size"])
    classifier_hidden = _int_list(fixture["classifier_hidden_size"])
    num_classes = _int_list(fixture["num_classes"])

    encoder = SimpleSequenceEncoder(
        in_features=in_features,
        hidden_sizes=hidden_sizes,
        transform="GRU",
        dropout=0.0,
        want_normalization=False,
        activation="",
    )
    bottleneck = LinearBottleneck(
        in_features=encoder.out_features, hidden_size=bottleneck_size
    )
    classifier = DeepLSTMClassifier(
        in_features=bottleneck.out_features,
        num_classes_per_dim=num_classes,
        hidden_sizes=classifier_hidden,
        dropout=0.5,
    )
    model = EncoderClassifierComposite(
        encoder=encoder, bottleneck=bottleneck, classifier=classifier
    )
    load_matlab_composite_weights(fixture, model)
    model.eval()
    return model


# ───────────────────────── Sanity ─────────────────────────


def test_fixture_layout(fixture: dict) -> None:
    """The composite fixture exposes the keys the test relies on."""
    for key in (
        "in_features",
        "hidden_sizes",
        "bottleneck_size",
        "classifier_hidden_size",
        "num_classes",
        "input",
        "weights",
        "expected",
    ):
        assert key in fixture, f"Fixture missing key {key!r}."


def test_bottleneck_weights_loaded(
    composite: EncoderClassifierComposite, fixture: dict
) -> None:
    """The bottleneck FC received MATLAB's fc_OUT_BottleNeck weights verbatim."""
    record = fixture["weights"][0, 0]
    ml_w = np.asarray(getattr(record, "fc_OUT_BottleNeck__Weights"))
    ml_b = np.asarray(getattr(record, "fc_OUT_BottleNeck__Bias")).ravel()
    np.testing.assert_allclose(
        composite.bottleneck.linear.weight.detach().numpy(), ml_w, rtol=0, atol=0
    )
    np.testing.assert_allclose(
        composite.bottleneck.linear.bias.detach().numpy(), ml_b, rtol=0, atol=0
    )


# ───────────────────────── Forward parity ─────────────────────────


def test_composite_forward_matches_matlab(
    composite: EncoderClassifierComposite, fixture: dict
) -> None:
    """Per-dim logits match MATLAB's pre-softmax fc outputs within fp32."""
    x_ctb = np.asarray(fixture["input"], dtype=np.float32)
    x_torch = torch.from_numpy(matlab_ctb_to_pytorch_btc(x_ctb)).float()

    with torch.no_grad():
        logits_per_dim = composite(x_torch)

    expected = fixture["expected"][0, 0]
    num_dims = _scalar(fixture["num_dims"])
    assert len(logits_per_dim) == num_dims

    max_diffs = []
    for d in range(num_dims):
        py = logits_per_dim[d].numpy()  # (B, T, K_d)
        ml_cbt = np.asarray(getattr(expected, f"logits_{d + 1}"), dtype=np.float32)
        ml_btc = matlab_cbt_to_pytorch_btc(ml_cbt)  # (B, T, K_d)
        assert py.shape == ml_btc.shape, (
            f"Dim {d + 1}: Python shape {py.shape} != MATLAB {ml_btc.shape}"
        )
        max_diffs.append(float(np.max(np.abs(py - ml_btc))))
        np.testing.assert_allclose(
            py,
            ml_btc,
            rtol=1e-5,
            atol=1e-5,
            err_msg=(
                f"Dim {d + 1} composite logits diverge from MATLAB. "
                f"Max abs diff: {max_diffs[-1]:.3e}"
            ),
        )
    # Surface the achieved precision in -v output for future reference.
    print(f"composite per-dim max abs diff: {max_diffs}")
