"""T3 — stratification strata IDs match MATLAB reference.

This test compares per-trial group IDs produced by
:func:`neural_data_decoding.data.stratification.stratify` against the
``PartitionGroups`` array stored in a MATLAB-generated reference fixture.

The reference fixture is produced by
``scripts/prepare_golden_fixtures.py --milestone 0`` (which runs MATLAB
in batch mode against a small fixture epoch). If the fixture is not
present on disk, the test skips with an informative message rather than
failing — fresh checkouts that haven't yet generated fixtures should
still see a green suite.

See ADR 001 for why strata-ID parity is treated as a T3 gate rather than
a strict bit-exact requirement.
"""

from __future__ import annotations

from pathlib import Path

import pytest


@pytest.mark.parity
def test_stratification_matches_matlab_reference(
    reference_partitions_dir: Path,
) -> None:
    """Per-trial group IDs match a MATLAB-generated ``KFoldPartition``.

    The fixture is named ``synthetic_easy_partition.mat`` by convention
    and is generated by ``scripts/prepare_golden_fixtures.py`` — once that
    script's Milestone-0 branch is wired up to write the file.
    """
    fixture = reference_partitions_dir / "synthetic_easy_partition.mat"
    if not fixture.is_file():
        pytest.skip(
            f"Reference fixture not present: {fixture}\n"
            f"Regenerate locally with:\n"
            f"    python scripts/prepare_golden_fixtures.py --milestone 0"
        )

    # When the fixture exists, the actual comparison logic lives here.
    # That code can't be written before a fixture format is finalized, so it
    # remains a stub. The skip above ensures CI stays green.
    pytest.fail(
        "Fixture exists but the parity-comparison logic is not yet implemented. "
        "This will land alongside the MATLAB-side fixture generator in "
        "scripts/prepare_golden_fixtures.py."
    )
