"""T2 — VAE-core parity: ELBO loss + sampling layer vs MATLAB.

Loads ``tests/fixtures/golden_weights/elbo_t2.mat`` (generated by
``scripts/generate_t2_elbo_fixture.m``) and reproduces every MATLAB value
with the Python kernels:

* :func:`~neural_data_decoding.training.losses.elbo.masked_mse_reconstruction_loss`
  vs ``cgg_lossELBO_v2``'s reconstruction term — the NaN-mask **batch-size**
  normalization (Critical Note #38, verified empirically).
* :func:`~neural_data_decoding.training.losses.elbo.kl_divergence_loss`
  vs the KL term.
* :func:`~neural_data_decoding.training.losses.elbo.per_channel_reconstruction_loss`
  vs the per-area telemetry loop.
* :class:`~neural_data_decoding.models.layers.sampling.SamplingLayer`
  in eval mode vs ``cgg_samplingLayer.predict`` (deterministic ``Z = mu``).

Skips cleanly when the fixture is absent.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import torch

from neural_data_decoding.models.layers.sampling import SamplingLayer
from neural_data_decoding.training.losses.elbo import (
    kl_divergence_loss,
    masked_mse_reconstruction_loss,
    per_channel_reconstruction_loss,
)


FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent
    / "fixtures"
    / "golden_weights"
    / "elbo_t2.mat"
)


def _scalar(v) -> float:
    return float(np.asarray(v).reshape(-1)[0])


@pytest.fixture(scope="module")
def fixture() -> dict:
    """Load the ELBO/sampling fixture once per module run."""
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"ELBO fixture missing: {FIXTURE_PATH}. Regenerate with: "
            "matlab -batch \"run('scripts/generate_t2_elbo_fixture.m')\""
        )
    return scipy.io.loadmat(str(FIXTURE_PATH))


# ───────────────────────── Reconstruction ─────────────────────────


def test_reconstruction_matches_matlab(fixture: dict) -> None:
    """Masked-MSE reconstruction matches MATLAB's 0.5*l2loss (batch-size norm)."""
    # SSCTB → batch is the last axis (index 4).
    y = torch.from_numpy(np.asarray(fixture["Y"], dtype=np.float64))
    t = torch.from_numpy(np.asarray(fixture["T_target"], dtype=np.float64))
    loss = masked_mse_reconstruction_loss(y, t, batch_dim=4)
    np.testing.assert_allclose(
        float(loss),
        _scalar(fixture["loss_Reconstruction"]),
        rtol=1e-6,
        atol=1e-6,
    )


def test_reconstruction_uses_batch_not_masksum_normalization(fixture: dict) -> None:
    """Guard against the mask-sum regression (Critical Note #38).

    If the kernel divided by ``mask.sum()`` instead of batch size, the
    value would differ from MATLAB by the ratio (mask.sum() / batch). This
    test recomputes the wrong-denominator value and asserts the kernel does
    NOT produce it.
    """
    y = torch.from_numpy(np.asarray(fixture["Y"], dtype=np.float64))
    t = torch.from_numpy(np.asarray(fixture["T_target"], dtype=np.float64))
    mask = ~torch.isnan(t)
    diff = torch.where(mask, y - t, torch.zeros_like(y))
    sq_sum = float((diff**2).sum())
    wrong_masksum = 0.5 * sq_sum / float(mask.sum())  # the rejected formula
    correct = float(masked_mse_reconstruction_loss(y, t, batch_dim=4))
    assert not np.isclose(correct, wrong_masksum, rtol=1e-6), (
        "Reconstruction loss matched the mask-sum normalization — "
        "regression of Critical Note #38."
    )


def test_per_channel_reconstruction_matches_matlab(fixture: dict) -> None:
    """Per-channel reconstruction matches MATLAB's per-area loop."""
    y = torch.from_numpy(np.asarray(fixture["Y"], dtype=np.float64))
    t = torch.from_numpy(np.asarray(fixture["T_target"], dtype=np.float64))
    # SSCTB: channel is axis 2, batch is axis 4.
    per_channel = per_channel_reconstruction_loss(
        y, t, channel_dim=2, batch_dim=4
    )
    py = np.array([float(v) for v in per_channel])
    ml = np.asarray(fixture["loss_Reconstruction_perchannel"], dtype=np.float64).ravel()
    np.testing.assert_allclose(py, ml, rtol=1e-6, atol=1e-6)


def test_per_channel_sums_to_total(fixture: dict) -> None:
    """Sanity: per-channel losses sum to the total reconstruction loss."""
    per_channel = np.asarray(
        fixture["loss_Reconstruction_perchannel"], dtype=np.float64
    ).ravel()
    np.testing.assert_allclose(
        per_channel.sum(), _scalar(fixture["loss_Reconstruction"]), rtol=1e-6
    )


# ───────────────────────── KL ─────────────────────────


def test_kl_matches_matlab(fixture: dict) -> None:
    """KL divergence matches MATLAB (sum over channel, mean over batch×time)."""
    # Latent CBT → channel is axis 0.
    mu = torch.from_numpy(np.asarray(fixture["mu"], dtype=np.float64))
    logvar = torch.from_numpy(np.asarray(fixture["logSigmaSq"], dtype=np.float64))
    loss = kl_divergence_loss(mu, logvar, channel_dim=0)
    np.testing.assert_allclose(
        float(loss), _scalar(fixture["loss_KL"]), rtol=1e-6, atol=1e-6
    )


# ───────────────────────── Sampling layer ─────────────────────────


def test_sampling_predict_is_deterministic_and_matches_matlab(fixture: dict) -> None:
    """Eval-mode SamplingLayer returns Z=mu, matching cgg_samplingLayer.predict."""
    x = torch.from_numpy(np.asarray(fixture["X_sampling"], dtype=np.float64))
    layer = SamplingLayer(channel_dim=0)  # X_sampling is CBT → channel axis 0
    layer.eval()
    z, mu, logvar = layer(x)

    ml_z = np.asarray(fixture["Z_pred"], dtype=np.float64)
    ml_mu = np.asarray(fixture["mu_pred"], dtype=np.float64)
    ml_logvar = np.asarray(fixture["logvar_pred"], dtype=np.float64)

    # Deterministic: Z == mu.
    np.testing.assert_array_equal(z.numpy(), mu.numpy())
    # Matches MATLAB's split + deterministic predict.
    np.testing.assert_allclose(z.numpy(), ml_z, rtol=1e-6, atol=1e-6)
    np.testing.assert_allclose(mu.numpy(), ml_mu, rtol=1e-6, atol=1e-6)
    np.testing.assert_allclose(logvar.numpy(), ml_logvar, rtol=1e-6, atol=1e-6)


def test_sampling_train_mode_is_stochastic() -> None:
    """Train-mode SamplingLayer draws different Z across calls (reparameterized)."""
    torch.manual_seed(0)
    layer = SamplingLayer(channel_dim=-1)
    layer.train()
    x = torch.randn(2, 4, 8)  # latent = 4
    z1, _, _ = layer(x)
    z2, _, _ = layer(x)
    assert not torch.equal(z1, z2), "Train-mode sampling should be stochastic."


def test_sampling_eval_mode_is_repeatable() -> None:
    """Eval-mode SamplingLayer gives identical Z across calls (Critical Note #35)."""
    layer = SamplingLayer(channel_dim=-1)
    layer.eval()
    x = torch.randn(2, 4, 8)
    z1, _, _ = layer(x)
    z2, _, _ = layer(x)
    assert torch.equal(z1, z2), "Eval-mode sampling must be deterministic."
