% scripts/generate_t2_confidence_fixture.m
%
% Milestone C #3 — confidence PD-controller T2 parity fixture.
%
% Critical Note #29 in the migration plan flags cgg_lossConfidence.m as the
% **highest-risk port** in the migration: five subtleties packed into one
% kernel, each silently parity-loss-prone if the Python port drifts. This
% script generates focused fixtures probing each subtlety in isolation.
%
% Each case is saved as a sub-struct (case_A, case_B_*, case_C_*). The
% Python parity test reproduces each output with the apply_confidence_routing
% kernel.
%
% Subtleties exercised:
%   1. Multiplicative conjunction (Eq. 1): TotalConf = TaskConf .* TrialConf
%   2. ConfidenceDropout: tested Python-only via explicit mask (not MATLAB
%      RNG-reproducibility); the fixtures use ConfidenceDropout=1.0 so the
%      MATLAB mask is always False and dropped == original — isolating the
%      deterministic math.
%   3. Prediction-to-truth interpolation (Eq. 2): Y' = c.*Y + (1-c).*T
%   4. Stop-gradient on history: Python-only (autograd-graph check)
%   5. BatchFraction-governed EMA (Eq. 7): Updated = Hist*(1-γ) + BatchMean*γ
%
% Loss type: 'L1' — clean arithmetic for parity, avoids CrossEntropy edge
% cases at scalar inputs. The orchestrator (Milestone C #4) will wire
% whatever LossType the config asks for.

clear; close all;

% ───────────────────────── Path setup ─────────────────────────
addpath(fileparts(mfilename('fullpath')));
ndd_add_matlab_paths();
thisDir = fileparts(mfilename('fullpath'));
projDir = fullfile(thisDir, '..');

rng(29, 'twister');  % seed for reproducibility (subtlety #29)

% ───────────────────────── Shared inputs ─────────────────────────
B = 3;                 % batch
T = 5;                 % time
K = 4;                 % classes
% Sequence inputs (CBT in MATLAB). Same Y/T used across cases.
Y_seq = randn(K, B, T);     % logits/probs (we don't softmax — testing the kernel math)
T_seq = randn(K, B, T);     % "target" — synthetic, just needs valid math
% Trial confidence: scalar per trial per time (1 channel, B batch, T time).
TrialConf_seq = 0.2 + 0.6 * rand(1, B, T);  % values in [0.2, 0.8]
% Task confidence: per-class per time per batch.
TaskConf_seq  = 0.1 + 0.8 * rand(K, B, T);  % values in [0.1, 0.9]

% Wrap in dlarrays.
Y_dl         = dlarray(Y_seq,        'CBT');
T_dl         = dlarray(T_seq,        'CBT');
TrialConf_dl = dlarray(TrialConf_seq,'CBT');
TaskConf_dl  = dlarray(TaskConf_seq, 'CBT');

% ───────────────────────── Case A: Conjunction + Interpolation ─────────────────────────
% Probes subtleties #1 (conjunction) and #3 (interpolation).
% Dropout disabled (ConfidenceDropout=1.0 → mask always False → dropped == original).
% No EMA: WantDatasetConfidence=false. BatchFraction=1.0 (irrelevant). Loss='L1'.
[Y_A, LT_A, Ltrial_A, Ltask_A] = cgg_lossConfidence(Y_dl, T_dl, ...
    TrialConf_dl, TaskConf_dl, ...
    'WantDatasetConfidence', false, ...
    'BatchFraction', 1.0, ...
    'LossType', 'L1', ...
    'ConfidenceDropout', 1.0);
case_A = struct( ...
    'Y_in',               Y_seq, ...
    'T_in',               T_seq, ...
    'TrialConf_in',       TrialConf_seq, ...
    'TaskConf_in',        TaskConf_seq, ...
    'Y_out',              double(extractdata(Y_A)), ...
    'loss_Total',         double(extractdata(LT_A)), ...
    'loss_Trial',         double(extractdata(Ltrial_A)), ...
    'loss_Task',          double(extractdata(Ltask_A)) );
fprintf('Case A (conj+interp): loss_Total=%.6f loss_Trial=%.6f loss_Task=%.6f\n', ...
    case_A.loss_Total, case_A.loss_Trial, case_A.loss_Task);

% ───────────────────────── Case B: BatchFraction EMA cadence ─────────────────────────
% Probes subtlety #5. Three values of BatchFraction γ ∈ {0.1, 0.5, 1.0}.
% History initialized to a known scalar (0.7), then EMA-updated by the batch.
% Dropout disabled. LossType='L1'.
hist_init = 0.7;
hist_dl = dlarray(hist_init);

cases_B = struct();
for gamma = [0.1, 0.5, 1.0]
    [~, ~, Ltrial_B, ~] = cgg_lossConfidence(Y_dl, T_dl, ...
        TrialConf_dl, TaskConf_dl, ...
        'WantDatasetConfidence', true, ...
        'DatasetTrialConfidence', hist_dl, ...
        'BatchFraction', gamma, ...
        'LossType', 'L1', ...
        'ConfidenceDropout', 1.0);
    % Also extract the analytical updated EMA for the Trial branch so the
    % Python test can pin both the loss AND the EMA value.
    trial_last = cgg_getLastSequenceValue(TrialConf_dl);
    batch_mean = double(extractdata(mean(trial_last, 'all')));
    updated_ema = hist_init * (1 - gamma) + batch_mean * gamma;
    key = sprintf('gamma_%03d', round(gamma * 100));  % gamma_010, gamma_050, gamma_100
    cases_B.(key) = struct( ...
        'gamma',         gamma, ...
        'hist_init',     hist_init, ...
        'batch_mean',    batch_mean, ...
        'updated_ema',   updated_ema, ...
        'loss_Trial',    double(extractdata(Ltrial_B)) );
    fprintf('Case B (γ=%.2f): batch_mean=%.6f updated_ema=%.6f loss_Trial=%.6f\n', ...
        gamma, batch_mean, updated_ema, cases_B.(key).loss_Trial);
end

% ───────────────────────── Case C: WantBatchCorrection ─────────────────────────
% Probes the Eq. 10 gradient correction: rawLoss / BatchFraction.
% Same setup as Case B with γ=0.25, with/without correction.
gamma_C = 0.25;
[~, ~, Ltrial_noCorr, ~] = cgg_lossConfidence(Y_dl, T_dl, ...
    TrialConf_dl, TaskConf_dl, ...
    'WantDatasetConfidence', true, ...
    'DatasetTrialConfidence', hist_dl, ...
    'BatchFraction', gamma_C, ...
    'LossType', 'L1', ...
    'WantBatchCorrection', false, ...
    'ConfidenceDropout', 1.0);
[~, ~, Ltrial_corr, ~] = cgg_lossConfidence(Y_dl, T_dl, ...
    TrialConf_dl, TaskConf_dl, ...
    'WantDatasetConfidence', true, ...
    'DatasetTrialConfidence', hist_dl, ...
    'BatchFraction', gamma_C, ...
    'LossType', 'L1', ...
    'WantBatchCorrection', true, ...
    'ConfidenceDropout', 1.0);
case_C = struct( ...
    'gamma',                  gamma_C, ...
    'hist_init',              hist_init, ...
    'loss_Trial_noCorr',      double(extractdata(Ltrial_noCorr)), ...
    'loss_Trial_corr',        double(extractdata(Ltrial_corr)) );
fprintf('Case C (γ=%.2f): noCorr=%.6f corr=%.6f ratio=%.6f (expected 1/γ=%.4f)\n', ...
    gamma_C, case_C.loss_Trial_noCorr, case_C.loss_Trial_corr, ...
    case_C.loss_Trial_corr / case_C.loss_Trial_noCorr, 1/gamma_C);

% ───────────────────────── Case D: Conjunction without dropout DISCRIMINATES Total path ─────────────────────────
% Verify TotalConfidence == TaskConf_last .* TrialConf_last by checking loss_Total
% is computed on the correct conjuncted value. With WantDatasetConfidence=false,
% loss_Total = l1loss(mean(TotalConf, 'all'), 1).
trial_last_arr = cgg_getLastSequenceValue(TrialConf_dl);
task_last_arr  = cgg_getLastSequenceValue(TaskConf_dl);
total_expected = task_last_arr .* trial_last_arr;
total_mean_expected = double(extractdata(mean(total_expected, 'all')));
loss_total_expected = abs(total_mean_expected - 1);  % L1
case_D = struct( ...
    'trial_last',         double(extractdata(trial_last_arr)), ...
    'task_last',          double(extractdata(task_last_arr)), ...
    'total_expected',     double(extractdata(total_expected)), ...
    'total_mean_expected', total_mean_expected, ...
    'loss_total_analytical', loss_total_expected );
fprintf('Case D (analytical): total_mean_expected=%.6f loss_total_analytical=%.6f\n', ...
    total_mean_expected, loss_total_expected);

% ───────────────────────── Save fixture ─────────────────────────
fixture = struct( ...
    'B', B, 'T', T, 'K', K, ...
    'case_A', case_A, ...
    'cases_B', cases_B, ...
    'case_C', case_C, ...
    'case_D', case_D, ...
    'hist_init', hist_init);

outDir = fullfile(projDir, 'tests', 'fixtures', 'golden_weights');
if ~isfolder(outDir); mkdir(outDir); end
outPath = fullfile(outDir, 'confidence_t2.mat');
save(outPath, '-struct', 'fixture', '-v7');
fprintf('Wrote %s\n', outPath);
